// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4t-FGvJ1IXlQg91ynPsJ1Jmr1gL0YqSg',
    appId: '1:296470230370:web:db319e389168315d41683b',
    messagingSenderId: '296470230370',
    projectId: 'social-82ea9',
    authDomain: 'social-82ea9.firebaseapp.com',
    storageBucket: 'social-82ea9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi1OKtM98pUyKiOK-JJjH7A_XLgI9jGJQ',
    appId: '1:296470230370:android:d90ebe8b82b274fe41683b',
    messagingSenderId: '296470230370',
    projectId: 'social-82ea9',
    storageBucket: 'social-82ea9.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4t-FGvJ1IXlQg91ynPsJ1Jmr1gL0YqSg',
    appId: '1:296470230370:web:3caa1bcc931d152941683b',
    messagingSenderId: '296470230370',
    projectId: 'social-82ea9',
    authDomain: 'social-82ea9.firebaseapp.com',
    storageBucket: 'social-82ea9.appspot.com',
  );
}
